---
abstract: 'One, Two, さーん'
author:
  - 'Kazuhiro Osawa <ko@yappo.ne.jp>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.750'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Acme-NabeAtzz
no_index:
  directory:
    - inc
    - t
requires:
  XSLoader: 0
version: 0.01
